title: Kritik Mahesh Kumar
logo: "C:\Users\kriti\OneDrive\Desktop\kritik.png"
description:Developer passionate about AI, robotics, and innovative technologies. Focused on continuous learning, 
problem-solving, and building impactful solutions.
#show_downloads: true
theme: jekyll-theme-minimal
