title: Kritik Mahesh Kumar
logo: C:\Users\kriti\OneDrive\Desktop\Kritik Co-Lead.jpeg
description:Developer passionate about AI, robotics, and innovative technologies. Focused on continuous learning, 
problem-solving, and building impactful solutions.
show_downloads: true
theme: jekyll-theme-minimal
