title:   Kritik Mahesh Kumar
logo: C:\Users\kriti\OneDrive\Desktop\Kritik Co-Lead.jpeg
description: "Passionate developer | AI enthusiast | Coffee-powered coder ☕"
theme: jekyll-theme-minimal-dark
author:
  name: Kritik Mahesh Kumar
  email: Kritikmahesh@gmail.com
